### ISSUE TITLE
question about video jitter

### ISSUE THREAD

**Issue by Czh19** [Goluck-Konuko/deep_animation_codec#1]
Hello!
I have run your code successfully.But when i use the reconstructed image to make a video which has a jitter question.
And I find it maybe caused by the quantize function,it turn the data from float32 to int8 to float32 which bring the loss of accuracy.
I do not know if I find the right reason,
How do you solve this question, I will be thankful if you can tell me.

**Comment by Goluck-Konuko** [comment]
It's true the quantization process introduces significant reduction in quality. And we kinda left it deliberately unoptimized as it is. However, there are a couple ways we identified to fix this.
1. Perform the quantization on a keypoint residuals between the target and an unquantized référence.
2. Train the keypoint détector with quantization awareness.
3. Introduce a learned context model for the motion keypoints and subsequently use torchac for the entropy coding.

**Comment by Czh19** [comment]
> It's true the quantization process introduces significant reduction in quality. And we kinda left it deliberately unoptimized as it is. However, there are a couple ways we identified to fix this.
> 
>     1. Perform the quantization on a keypoint residuals between the target and an unquantized référence.
> 
>     2. Train the keypoint détector with quantization awareness.
> 
>     3. Introduce a learned context model for the motion keypoints and subsequently use torchac for the entropy coding.

oh! Thanks for your reply!
I found you have Perform the quantization on a keypoint residuals between the target and an unquantized référence in your quantize function of your code.
And I also download your dac_pth to reconstruct video,but video jitter still exists.
I do not know if you have solved quantization problem through these ways.
Thanks again.
